[build]
publish = "Homepage"
command = ""

[[redirects]]
from = "/about_us"
to = "/about_us/About_us.html"
status = 200

[[redirects]]
from = "/shop"
to = "/Shop/shop.html"
status = 200

[[redirects]]
from = "/Schematics"
to = "/schematics/Schematics.html"
status = 200

[[redirects]]
from = "/sponsorship"
to = "/Sponsorship/sponsorship.html"
status = 200
