[build]
command = ""
publish = "dist"

# Basis-Redirects für HTML5 PushState (SPA Fallback)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Spezifische Redirects für Ihre Seiten
[[redirects]]
from = "/home"
to = "/Homepage/Homepage.html"
status = 200

[[redirects]]
from = "/about"
to = "/about_us/About_us.html"
status = 200

[[redirects]]
from = "/sponsors"
to = "/Sponsorship/sponsorship.html"
status = 200

[[redirects]]
from = "/design"
to = "/schematics/Schematics.html"
status = 200

[[redirects]]
from = "/store"
to = "/Shop/shop.html"
status = 200

# Asset Caching
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600"
