[build]
command = ""  # Leer lassen, da kein Build-Schritt nötig
publish = "." # Aktuellen Ordner deployen

[[redirects]]
from = "/Homepage"
to = "/Homepage/Homepage.html"
status = 200

[[redirects]]
from = "/About_us"
to = "/About_us/About_us.html"
status = 200

[[redirects]]
from = "/Schematics"
to = "/Schematics/schematics.html"
status = 200

[[redirects]]
from = "/Shop"
to = "/Shop/shop.html"
status = 200

[[redirects]]
from = "/Sponsorship"
to = "/Sponsorship/sponsorship.html"
status = 200

[[redirects]]
from = "/"
to = "/Homepage/Homepage.html"
status = 200
