[build]
publish = "."
command = ""

[[redirects]]
from = "/*"
to = "/Homepage/Homepage.html"
status = 200
force = true

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600"
X-Frame-Options = "DENY"
